GET http://localhost:3001/api/people/

###

GET http://localhost:3001/api/people/

###

DELETE http://localhost:3001/api/people/5d9dfa2a0968e111f48e02dc

###

PUT http://localhost:3001/api/people/5d9603c0a6ffb6314e43371a
content-type: application/json

{
    "name": "Aku Ankka",
    "number": "123",
    "id": "5d9603c0a6ffb6314e43371a"
}

###

POST http://localhost:3001/api/people/
content-type: application/json

{
    "name": "Aku Ankka",
    "number": "3131"
}

###

POST http://localhost:3001/api/people/
content-type: application/json

{
    "number": "313"
}

###

POST http://localhost:3001/api/people/
content-type: application/json

{
    "name": "",
    "number": "313"
}

###

POST http://localhost:3001/api/people/
content-type: application/json

{
    "name": "Aku"
}

###

POST http://localhost:3001/api/people/
content-type: application/json

{
    "name": "Aku",
    "number": ""
}