GET https://phonenumbers-anttiheimonen.herokuapp.com/api/people/

###

DELETE https://phonenumbers-anttiheimonen.herokuapp.com/api/people/4

###

POST https://phonenumbers-anttiheimonen.herokuapp.com/api/people/
content-type: application/json

{
    "name": "Aku Ankka",
    "number": "313123123"
}

###

POST https://phonenumbers-anttiheimonen.herokuapp.com/api/people/
content-type: application/json

{
    "number": "313"
}

###

POST https://phonenumbers-anttiheimonen.herokuapp.com/api/people/
content-type: application/json

{
    "name": "313"
}
